zFramework.Core.Cloth.Hairs = [
    [
        {ID: 0, name: "Rase de pres", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"},
        {ID: 37, name: "Court"},
        {ID: 38, name: "Faux Hawk", collection: "multiplayer_overlays", overlay: "NG_M_Hair_002"},
        {ID: 39, name: "Hipster", collection: "multiplayer_overlays", overlay: "NG_M_Hair_003"},
        {ID: 40, name: "Side Parting", collection: "multiplayer_overlays", overlay: "NG_M_Hair_004"},
        {ID: 41, name: "Shorter Cut", collection: "multiplayer_overlays", overlay: "NG_M_Hair_005"},
        {ID: 42, name: "Biker", collection: "multiplayer_overlays", overlay: "NG_M_Hair_006"},
        {ID: 43, name: "Ponytail", collection: "multiplayer_overlays", overlay: "NG_M_Hair_007"},
        {ID: 44, name: "Cornrows", collection: "multiplayer_overlays", overlay: "NG_M_Hair_008"},
        {ID: 45, name: "Slicked", collection: "multiplayer_overlays", overlay: "NG_M_Hair_009"},
        {ID: 46, name: "Short Brushed", collection: "multiplayer_overlays", overlay: "NG_M_Hair_013"},
        {ID: 47, name: "Spikey", collection: "multiplayer_overlays", overlay: "NG_M_Hair_002"},
        {ID: 48, name: "Caesar", collection: "multiplayer_overlays", overlay: "NG_M_Hair_011"},
        {ID: 49, name: "Chopped", collection: "multiplayer_overlays", overlay: "NG_M_Hair_012"},
        {ID: 50, name: "Dreads", collection: "multiplayer_overlays", overlay: "NG_M_Hair_014"},
        {ID: 51, name: "Long Hair", collection: "multiplayer_overlays", overlay: "NG_M_Hair_015"},
        {ID: 52, name: "Shaggy Curls", collection: "multiplayer_overlays", overlay: "NGBea_M_Hair_000"},
        {ID: 53, name: "Surfer Dude", collection: "multiplayer_overlays", overlay: "NGBea_M_Hair_001"},
        {ID: 54, name: "Short Side Part", collection: "multiplayer_overlays", overlay: "NGBus_M_Hair_000"},
        {ID: 55, name: "High Slicked Sides", collection: "multiplayer_overlays", overlay: "NGBus_M_Hair_001"},
        {ID: 56, name: "Long Slicked", collection: "multiplayer_overlays", overlay: "NGHip_M_Hair_000"},
        {ID: 57, name: "Hipster Youth", collection: "multiplayer_overlays", overlay: "NGHip_M_Hair_001"},
        {ID: 58, name: "Mullet", collection: "multiplayer_overlays", overlay: "NGInd_M_Hair_000"},
        {ID: 59, name: "Classic Cornrows", collection: "mplowrider_overlays", overlay: "LR_M_Hair_000"},
        {ID: 60, name: "Palm Cornrows", collection: "mplowrider_overlays", overlay: "LR_M_Hair_001"},
        {ID: 61, name: "Lightning Cornrows", collection: "mplowrider_overlays", overlay: "LR_M_Hair_002"},
        {ID: 62, name: "Whipped Cornrows", collection: "mplowrider_overlays", overlay: "LR_M_Hair_003"},
        {ID: 63, name: "Zig Zag Cornrows", collection: "mplowrider2_overlays", overlay: "LR_M_Hair_004"},
        {ID: 64, name: "Snail Cornrows", collection: "mplowrider2_overlays", overlay: "LR_M_Hair_005"},
        {ID: 65, name: "Hightop", collection: "mplowrider2_overlays", overlay: "LR_M_Hair_006"},
        {ID: 66, name: "Loose Swept Back", collection: "mpbiker_overlays", overlay: "MP_Biker_Hair_000_M"},
        {ID: 67, name: "Undercut Swept Back", collection: "mpbiker_overlays", overlay: "MP_Biker_Hair_001_M"},
        {ID: 68, name: "Undercut Swept Side", collection: "mpbiker_overlays", overlay: "MP_Biker_Hair_002_M"},
        {ID: 69, name: "Spiked Mohawk", collection: "mpbiker_overlays", overlay: "MP_Biker_Hair_003_M"},
        {ID: 70, name: "Mod", collection: "mpbiker_overlays", overlay: "MP_Biker_Hair_004_M"},
        {ID: 71, name: "Layered Mod", collection: "mpbiker_overlays", overlay: "MP_Biker_Hair_005_M"},
        {ID: 72, name: "Flattop", collection: "mpgunrunning_overlays", overlay: "MP_Gunrunning_Hair_M_000_M"},
        {ID: 73, name: "Military Buzzcut", collection: "mpgunrunning_overlays", overlay: "MP_Gunrunning_Hair_M_001_M"},
        {ID: 74, name: "Banane", collection: "mpgunrunning_overlays", overlay: "MP_Gunrunning_Hair_M_001_M"},
        {ID: 75, name: "Longue queue", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"},
        {ID: 76, name: "Chignon", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"},
        {ID: 77, name: "Queue courte", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"},
        {ID: 78, name: "Biker", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"},
        {ID: 79, name: "Pecno", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"},
        {ID: 80, name: "Macbeat"},
        {ID: 81, name: "Trunks", collection: "multiplayer_overlays", overlay: "NG_M_Hair_012"},
        {ID: 82, name: "Buzz", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"},
        {ID: 83, name: "Sage", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"},
        {ID: 84, name: "Boucle", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"}
    ],
    [
        {ID: 0, name: "Crâne rase", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"},
        {ID: 39, name: "Short", collection: "multiplayer_overlays", overlay: "NG_F_Hair_001"},
        {ID: 40, name: "Layered Bob", collection: "multiplayer_overlays", overlay: "NG_F_Hair_002"},
        {ID: 41, name: "Pigtails", collection: "multiplayer_overlays", overlay: "NG_F_Hair_003"},
        {ID: 42, name: "Ponytail", collection: "multiplayer_overlays", overlay: "NG_F_Hair_004"},
        {ID: 43, name: "Braided Mohawk", collection: "multiplayer_overlays", overlay: "NG_F_Hair_005"},
        {ID: 44, name: "Braids", collection: "multiplayer_overlays", overlay: "NG_F_Hair_006"},
        {ID: 45, name: "Bob", collection: "multiplayer_overlays", overlay: "NG_F_Hair_007"},
        {ID: 46, name: "Faux Hawk", collection: "multiplayer_overlays", overlay: "NG_F_Hair_008"},
        {ID: 47, name: "French Twist", collection: "multiplayer_overlays", overlay: "NG_F_Hair_009"},
        {ID: 48, name: "Long Bob", collection: "multiplayer_overlays", overlay: "NG_F_Hair_010"},
        {ID: 49, name: "Loose Tied", collection: "multiplayer_overlays", overlay: "NG_F_Hair_011"},
        {ID: 50, name: "Pixie", collection: "multiplayer_overlays", overlay: "NG_F_Hair_012"},
        {ID: 51, name: "Shaved Bangs", collection: "multiplayer_overlays", overlay: "NG_F_Hair_013"},
        {ID: 52, name: "Top Knot", collection: "multiplayer_overlays", overlay: "NG_M_Hair_014"},
        {ID: 53, name: "Wavy Bob", collection: "multiplayer_overlays", overlay: "NG_M_Hair_015"},
        {ID: 54, name: "Messy Bun", collection: "multiplayer_overlays", overlay: "NGBea_F_Hair_000"},
        {ID: 55, name: "Pin Up Girl", collection: "multiplayer_overlays", overlay: "NGBea_F_Hair_001"},
        {ID: 56, name: "Tight Bun", collection: "multiplayer_overlays", overlay: "NG_F_Hair_007"},
        {ID: 57, name: "Twisted Bob", collection: "multiplayer_overlays", overlay: "NGBus_F_Hair_000"},
        {ID: 58, name: "Flapper Bob", collection: "multiplayer_overlays", overlay: "NGBus_F_Hair_001"},
        {ID: 59, name: "Big Bangs", collection: "multiplayer_overlays", overlay: "NGBea_F_Hair_001"},
        {ID: 60, name: "Braided Top Knot", collection: "multiplayer_overlays", overlay: "NGHip_F_Hair_000"},
        {ID: 61, name: "Mullet", collection: "multiplayer_overlays", overlay: "NGInd_F_Hair_000"},
        {ID: 62, name: "Pinched Cornrows", collection: "mplowrider_overlays", overlay: "LR_F_Hair_000"},
        {ID: 63, name: "Leaf Cornrows", collection: "mplowrider_overlays", overlay: "LR_F_Hair_001"},
        {ID: 64, name: "Zig Zag Cornrows", collection: "mplowrider_overlays", overlay: "LR_F_Hair_002"},
        {ID: 65, name: "Pigtail Bangs", collection: "mplowrider2_overlays", overlay: "LR_F_Hair_003"},
        {ID: 66, name: "Wave Braids", collection: "mplowrider2_overlays", overlay: "LR_F_Hair_003"},
        {ID: 67, name: "Coil Braids", collection: "mplowrider2_overlays", overlay: "LR_F_Hair_004"},
        {ID: 68, name: "Rolled Quiff", collection: "mplowrider2_overlays", overlay: "LR_F_Hair_006"},
        {ID: 69, name: "Loose Swept Back", collection: "mpbiker_overlays", overlay: "MP_Biker_Hair_000_F"},
        {ID: 70, name: "Undercut Swept Back", collection: "mpbiker_overlays", overlay: "MP_Biker_Hair_001_F"},
        {ID: 71, name: "Undercut Swept Side", collection: "mpbiker_overlays", overlay: "MP_Biker_Hair_002_F"},
        {ID: 72, name: "Spiked Mohawk", collection: "mpbiker_overlays", overlay: "MP_Biker_Hair_003_F"},
        {ID: 73, name: "Bandana and Braid", collection: "multiplayer_overlays", overlay: "NG_F_Hair_003"},
        {ID: 74, name: "Layered Mod", collection: "mpbiker_overlays", overlay: "MP_Biker_Hair_006_F"},
        {ID: 75, name: "Skinbyrd", collection: "mpbiker_overlays", overlay: "MP_Biker_Hair_004_F"},
        {ID: 76, name: "Neat Bun", collection: "mpgunrunning_overlays", overlay: "MP_Gunrunning_Hair_F_000_F"},
        {ID: 77, name: "Short Bob", collection: "mpgunrunning_overlays", overlay: "MP_Gunrunning_Hair_F_001_F"},
        {ID: 78, name: "Banane", collection: "mpgunrunning_overlays", overlay: "MP_Gunrunning_Hair_M_001_M"},
        {ID: 79, name: "Long", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"},
        {ID: 80, name: "Pony tails", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"},
        {ID: 81, name: "Court", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"},
        {ID: 82, name: "Long epaule", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"},
        {ID: 83, name: "Simpliste", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"},
        {ID: 84, name: "Cube", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"},
        {ID: 85, name: "Dread", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"},
        {ID: 86, name: "Classique"},
        {ID: 87, name: "Coiffure 09", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"},
        {ID: 88, name: "Coiffure 10", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"},
        {ID: 89, name: "Coiffure 11", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"},
        {ID: 90, name: "Coiffure 12", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"},
        {ID: 91, name: "Coiffure 13", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"},
        {ID: 92, name: "Coiffure 14", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"},
        {ID: 93, name: "Coiffure 15", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"},
        {ID: 94, name: "Coiffure 16", collection: "mpbeach_overlays", overlay: "FM_Hair_Fuzz"}
    ]
]

zFramework.Core.Cloth.Overlays = [
    ["mpbeach_overlays", "MP_Bea_M_Head_000"],
    ["multiplayer_overlays", "FM_Tat_Award_M_000"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_009_M"],
    ["mpbeach_overlays", "MP_Bea_M_Head_000"],
    ["mplowrider_overlays", "LR_F_Hair_000"],
    ["mplowrider_overlays", "LR_F_Hair_001"],
    ["mplowrider_overlays", "LR_F_Hair_002"],
    ["mpbeach_overlays", "MP_Bea_F_Neck_000"],
    ["mphipster_overlays", "FM_Hip_M_Tat_005"],
    ["mphipster_overlays", "FM_Hip_M_Tat_021"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_038_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_051_M"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_007"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_024"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_025"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_029"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_003_M"],
    ["mpbusiness_overlays", "MP_Buis_M_Neck_000"],
    ["mpbusiness_overlays", "MP_Buis_M_Neck_001"],
    ["mpbusiness_overlays", "MP_Buis_M_Neck_002"],
    ["mpbusiness_overlays", "MP_Buis_M_Neck_003"],
    ["mpbeach_overlays", "MP_Bea_M_Neck_000"],
    ["mpbeach_overlays", "MP_Bea_M_Neck_001"],
    ["mpbeach_overlays", "MP_Bea_M_Neck_002"],
    ["mphipster_overlays", "FM_Hip_M_Tat_005"],
    ["multiplayer_overlays", "FM_Tat_Award_M_001"],
    ["multiplayer_overlays", "FM_Tat_M_005"],
    ["multiplayer_overlays", "FM_Tat_M_006"],
    ["mphipster_overlays", "FM_Hip_M_Tat_003"],
    ["mphipster_overlays", "FM_Hip_M_Tat_007"],
    ["mphipster_overlays", "FM_Hip_M_Tat_015"],
    ["mphipster_overlays", "FM_Hip_M_Tat_016"],
    ["mphipster_overlays", "FM_Hip_M_Tat_027"],
    ["mphipster_overlays", "FM_Hip_M_Tat_028"],
    ["mphipster_overlays", "FM_Hip_M_Tat_034"],
    ["mphipster_overlays", "FM_Hip_M_Tat_039"],
    ["mphipster_overlays", "FM_Hip_M_Tat_048"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_012_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_053_M"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_000"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_020"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_021"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_004_M"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_025_M"],
    ["mplowrider_overlays", "MP_LR_Tat_005_M"],
    ["mplowrider_overlays", "MP_LR_Tat_006_M"],
    ["mplowrider2_overlays", "MP_LR_Tat_022_M"],
    ["mpluxe_overlays", "MP_LUXE_TAT_021_M"],
    ["mpluxe2_overlays", "MP_LUXE_TAT_005_M"],
    ["mpluxe2_overlays", "MP_LUXE_TAT_016_M"],
    ["mpluxe2_overlays", "MP_LUXE_TAT_028_M"],
    ["mpbusiness_overlays", "MP_Buis_M_LeftArm_000"],
    ["mpbusiness_overlays", "MP_Buis_M_LeftArm_001"],
    ["mpbeach_overlays", "MP_Bea_F_LArm_000"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_000"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_010"],
    ["multiplayer_overlays", "FM_Tat_M_015"],
    ["multiplayer_overlays", "FM_Tat_M_031"],
    ["multiplayer_overlays", "FM_Tat_M_041"],
    ["mpluxe_overlays", "MP_LUXE_TAT_009_M"],
    ["multiplayer_overlays", "FM_Tat_Award_M_015"],
    ["mphipster_overlays", "FM_Hip_M_Tat_037"],
    ["mphipster_overlays", "FM_Hip_M_Tat_043"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_016_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_020_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_020_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_024_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_025_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_035_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_045_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_055_M"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_008_M"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_015_M"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_016_M"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_027_M"],
    ["mpimportexport_overlays", "MP_MP_ImportExport_Tat_004_M"],
    ["mpimportexport_overlays", "MP_MP_ImportExport_Tat_008_M"],
    ["mplowrider_overlays", "MP_LR_Tat_026_M"],
    ["multiplayer_overlays", "FM_Tat_Award_M_007"],
    ["mplowrider2_overlays", "MP_LR_Tat_018_M"],
    ["mpluxe_overlays", "MP_LUXE_TAT_020_M"],
    ["mpluxe2_overlays", "MP_LUXE_TAT_018_M"],
    ["mpluxe2_overlays", "MP_LUXE_TAT_031_M"],
    ["mpbeach_overlays", "MP_Bea_F_LArm_001"],
    ["mpluxe2_overlays", "MP_LUXE_TAT_031_M"],
    ["mphipster_overlays", "FM_Hip_M_Tat_026"],
    ["mplowrider_overlays", "MP_LR_Tat_027_M"],
    ["mplowrider_overlays", "MP_LR_Tat_033_M"],
    ["mplowrider_overlays", "MP_LR_Tat_033_F"],
    ["multiplayer_overlays", "FM_Tat_M_038"],
    ["multiplayer_overlays", "FM_Tat_M_028"],
    ["multiplayer_overlays", "FM_Tat_M_018"],
    ["multiplayer_overlays", "FM_Tat_M_014"],
    ["new_overlays", "new_tattoo_01_M"],
    ["mplowrider2_overlays", "MP_LR_Tat_003_M"],
    ["mphipster_overlays", "FM_Hip_M_Tat_014"],
    ["mphipster_overlays", "FM_Hip_M_Tat_017"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_008"],
    ["mphipster_overlays", "FM_Hip_M_Tat_018"],
    ["mphipster_overlays", "FM_Hip_M_Tat_020"],
    ["mphipster_overlays", "FM_Hip_M_Tat_022"],
    ["mphipster_overlays", "FM_Hip_M_Tat_023"],
    ["mphipster_overlays", "FM_Hip_M_Tat_045"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_042_M"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_022"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_023"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_026"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_027"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_002_M"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_024_M"],
    ["mplowrider_overlays", "MP_LR_Tat_015_M"],
    ["mplowrider2_overlays", "MP_LR_Tat_003_M"],
    ["mplowrider2_overlays", "MP_LR_Tat_035_M"],
    ["mpluxe_overlays", "MP_LUXE_TAT_004_M"],
    ["mpluxe2_overlays", "MP_LUXE_TAT_010_M"],
    ["mpbusiness_overlays", "MP_Buis_M_RightArm_001"],
    ["multiplayer_overlays", "FM_Tat_Award_M_010"],
    ["mphipster_overlays", "FM_Hip_M_Tat_010"],
    ["multiplayer_overlays", "FM_Tat_Award_M_002"],
    ["multiplayer_overlays", "FM_Tat_M_000"],
    ["multiplayer_overlays", "FM_Tat_M_001"],
    ["multiplayer_overlays", "FM_Tat_M_003"],
    ["multiplayer_overlays", "FM_Tat_M_027"],
    ["multiplayer_overlays", "FM_Tat_M_047"],
    ["mphipster_overlays", "FM_Hip_M_Tat_001"],
    ["mphipster_overlays", "FM_Hip_M_Tat_036"],
    ["mphipster_overlays", "FM_Hip_M_Tat_044"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_007_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_014_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_033_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_046_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_047_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_049_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_054_M"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_003"],
    ["mpluxe2_overlays", "MP_LUXE_TAT_017_M"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_004"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_021_M"],
    ["mpimportexport_overlays", "MP_MP_ImportExport_Tat_003_M"],
    ["mpimportexport_overlays", "MP_MP_ImportExport_Tat_005_M"],
    ["mpimportexport_overlays", "MP_MP_ImportExport_Tat_006_M"],
    ["mpimportexport_overlays", "MP_MP_ImportExport_Tat_007_M"],
    ["mplowrider2_overlays", "MP_LR_Tat_028_M"],
    ["mpluxe_overlays", "MP_LUXE_TAT_013_M"],
    ["mpluxe_overlays", "MP_LUXE_TAT_019_M"],
    ["mpluxe2_overlays", "MP_LUXE_TAT_026_M"],
    ["mpbusiness_overlays", "MP_Buis_M_RightArm_000"],
    ["mpbeach_overlays", "MP_Bea_F_RArm_001"],
    ["mpbeach_overlays", "MP_Bea_F_Back_000"],
    ["mpbeach_overlays", "MP_Bea_F_Back_001"],
    ["mpbeach_overlays", "MP_Bea_F_Back_002"],
    ["multiplayer_overlays", "FM_Tat_Award_M_005"],
    ["multiplayer_overlays", "FM_Tat_Award_M_008"],
    ["multiplayer_overlays", "FM_Tat_Award_M_014"],
    ["multiplayer_overlays", "FM_Tat_Award_M_016"],
    ["multiplayer_overlays", "FM_Tat_Award_M_017"],
    ["multiplayer_overlays", "FM_Tat_Award_M_018"],
    ["multiplayer_overlays", "FM_Tat_Award_M_019"],
    ["multiplayer_overlays", "FM_Tat_M_009"],
    ["multiplayer_overlays", "FM_Tat_M_011"],
    ["multiplayer_overlays", "FM_Tat_M_013"],
    ["multiplayer_overlays", "FM_Tat_M_016"],
    ["multiplayer_overlays", "FM_Tat_M_019"],
    ["multiplayer_overlays", "FM_Tat_M_020"],
    ["multiplayer_overlays", "FM_Tat_M_030"],
    ["multiplayer_overlays", "FM_Tat_M_045"],
    ["multiplayer_overlays", "FM_Tat_M_046"],
    ["mphipster_overlays", "FM_Hip_M_Tat_000"],
    ["mphipster_overlays", "FM_Hip_M_Tat_006"],
    ["mphipster_overlays", "FM_Hip_M_Tat_011"],
    ["mphipster_overlays", "FM_Hip_M_Tat_012"],
    ["mphipster_overlays", "FM_Hip_M_Tat_024"],
    ["mphipster_overlays", "FM_Hip_M_Tat_025"],
    ["mphipster_overlays", "FM_Hip_M_Tat_030"],
    ["mphipster_overlays", "FM_Hip_M_Tat_031"],
    ["mphipster_overlays", "FM_Hip_M_Tat_032"],
    ["mphipster_overlays", "FM_Hip_M_Tat_041"],
    ["mphipster_overlays", "FM_Hip_M_Tat_046"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_006_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_008_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_011_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_017_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_021_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_030_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_043_M"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_005"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_006"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_011"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_013"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_015"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_000_M"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_001_M"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_013_M"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_014_M"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_018_M"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_019_M"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_022_M"],
    ["mpimportexport_overlays", "MP_MP_ImportExport_Tat_000_M"],
    ["mpimportexport_overlays", "MP_MP_ImportExport_Tat_001_M"],
    ["mpimportexport_overlays", "MP_MP_ImportExport_Tat_002_M"],
    ["mpimportexport_overlays", "MP_MP_ImportExport_Tat_009_M"],
    ["mpimportexport_overlays", "MP_MP_ImportExport_Tat_010_M"],
    ["mpimportexport_overlays", "MP_MP_ImportExport_Tat_011_M"],
    ["mplowrider_overlays", "MP_LR_Tat_004_M"],
    ["mplowrider_overlays", "MP_LR_Tat_009_M"],
    ["mplowrider_overlays", "MP_LR_Tat_010_M"],
    ["mplowrider_overlays", "MP_LR_Tat_014_M"],
    ["mplowrider_overlays", "MP_LR_Tat_021_M"],
    ["mplowrider2_overlays", "MP_LR_Tat_000_M"],
    ["mplowrider2_overlays", "MP_LR_Tat_008_M"],
    ["mplowrider2_overlays", "MP_LR_Tat_011_M"],
    ["mplowrider2_overlays", "MP_LR_Tat_031_M"],
    ["mplowrider2_overlays", "MP_LR_Tat_032_M"],
    ["mpluxe_overlays", "MP_LUXE_TAT_006_M"],
    ["mpluxe_overlays", "MP_LUXE_TAT_024_M"],
    ["mpluxe2_overlays", "MP_LUXE_TAT_029_M"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_009_M"],
    ["mpluxe2_overlays", "MP_LUXE_TAT_022_M"],
    ["mpbusiness_overlays", "MP_Buis_M_Back_000"],
    ["mpbeach_overlays", "MP_Bea_F_Back_000"],
    ["mpbeach_overlays", "MP_Bea_F_Back_001"],
    ["mpbeach_overlays", "MP_Bea_F_Back_002"],
    ["mpbeach_overlays", "MP_Bea_F_RSide_000"],
    ["mpbeach_overlays", "MP_Bea_F_Should_000"],
    ["mpbeach_overlays", "MP_Bea_F_Should_001"],
    ["mpbeach_overlays", "MP_Bea_F_Chest_000"],
    ["mpbeach_overlays", "MP_Bea_F_Chest_001"],
    ["mpbeach_overlays", "MP_Bea_F_Chest_002"],
    ["mpbeach_overlays", "MP_Bea_M_Chest_000"],
    ["mpbeach_overlays", "MP_Bea_M_Chest_001"],
    ["multiplayer_overlays", "FM_Tat_Award_M_003"],
    ["multiplayer_overlays", "FM_Tat_M_004"],
    ["multiplayer_overlays", "FM_Tat_Award_M_011"],
    ["multiplayer_overlays", "FM_Tat_Award_M_012"],
    ["multiplayer_overlays", "FM_Tat_Award_M_013"],
    ["multiplayer_overlays", "FM_Tat_M_012"],
    ["multiplayer_overlays", "FM_Tat_M_024"],
    ["multiplayer_overlays", "FM_Tat_M_025"],
    ["multiplayer_overlays", "FM_Tat_M_029"],
    ["multiplayer_overlays", "FM_Tat_M_034"],
    ["multiplayer_overlays", "FM_Tat_M_036"],
    ["multiplayer_overlays", "FM_Tat_M_044"],
    ["mphipster_overlays", "FM_Hip_M_Tat_002"],
    ["mphipster_overlays", "FM_Hip_M_Tat_013"],
    ["mphipster_overlays", "FM_Hip_M_Tat_029"],
    ["mphipster_overlays", "FM_Hip_M_Tat_033"],
    ["mphipster_overlays", "FM_Hip_M_Tat_035"],
    ["mphipster_overlays", "FM_Hip_M_Tat_047"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_000_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_001_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_003_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_005_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_010_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_013_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_018_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_019_M"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_010_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_023_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_026_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_029_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_031_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_032_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_034_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_039_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_041_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_050_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_052_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_058_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_059_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_060_M"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_009"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_016"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_017"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_018"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_019"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_028"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_012_M"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_017_M"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_020_M"],
    ["mplowrider_overlays", "MP_LR_Tat_001_M"],
    ["mplowrider_overlays", "MP_LR_Tat_002_M"],
    ["mplowrider_overlays", "MP_LR_Tat_013_M"],
    ["mplowrider_overlays", "MP_LR_Tat_026_M"],
    ["mplowrider2_overlays", "MP_LR_Tat_012_M"],
    ["mplowrider2_overlays", "MP_LR_Tat_016_M"],
    ["mplowrider2_overlays", "MP_LR_Tat_019_M"],
    ["mpluxe_overlays", "MP_LUXE_TAT_002_M"],
    ["mpluxe_overlays", "MP_LUXE_TAT_008_M"],
    ["mpluxe_overlays", "MP_LUXE_TAT_014_M"],
    ["mpluxe_overlays", "MP_LUXE_TAT_015_M"],
    ["mpluxe2_overlays", "MP_LUXE_TAT_002_M"],
    ["mpluxe2_overlays", "MP_LUXE_TAT_012_M"],
    ["mpluxe2_overlays", "MP_LUXE_TAT_025_M"],
    ["mpluxe2_overlays", "MP_LUXE_TAT_027_M"],
    ["mpbusiness_overlays", "MP_Buis_M_Stomach_000"],
    ["mpbusiness_overlays", "MP_Buis_M_Chest_000"],
    ["mpbusiness_overlays", "MP_Buis_M_Chest_001"],
    ["mpbeach_overlays", "MP_Bea_F_Chest_000"],
    ["mpbeach_overlays", "MP_Bea_F_Chest_001"],
    ["mpbeach_overlays", "MP_Bea_F_Chest_002"],
    ["mpbeach_overlays", "MP_Bea_F_Stom_000"],
    ["mpbeach_overlays", "MP_Bea_F_Stom_001"],
    ["mpbeach_overlays", "MP_Bea_F_Stom_002"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_029_M"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_028_M"],
    ["multiplayer_overlays", "FM_Tat_M_010"],
    ["multiplayer_overlays", "FM_Tat_Award_M_004"],
    ["new_overlays", "gtalife_johnny_torso_M"],
    ["multiplayer_overlays", "FM_Tat_M_033"],
    ["multiplayer_overlays", "FM_Tat_M_002"],
    ["multiplayer_overlays", "FM_Tat_M_008"],
    ["multiplayer_overlays", "FM_Tat_M_021"],
    ["multiplayer_overlays", "FM_Tat_M_023"],
    ["multiplayer_overlays", "FM_Tat_M_026"],
    ["multiplayer_overlays", "FM_Tat_M_032"],
    ["multiplayer_overlays", "FM_Tat_M_035"],
    ["multiplayer_overlays", "FM_Tat_M_037"],
    ["multiplayer_overlays", "FM_Tat_Award_M_009"],
    ["mphipster_overlays", "FM_Hip_M_Tat_019"],
    ["mphipster_overlays", "FM_Hip_M_Tat_040"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_002_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_015_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_027_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_036_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_037_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_044_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_056_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_057_M"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_001"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_002"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_005_M"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_007_M"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_011_M"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_023_M"],
    ["mplowrider_overlays", "MP_LR_Tat_007_M"],
    ["mplowrider_overlays", "MP_LR_Tat_020_M"],
    ["mplowrider2_overlays", "MP_LR_Tat_029_M"],
    ["mpluxe_overlays", "MP_LUXE_TAT_000_M"],
    ["mpluxe2_overlays", "MP_LUXE_TAT_011_M"],
    ["multiplayer_overlays", "FM_Tat_Award_M_006"],
    ["multiplayer_overlays", "FM_Tat_M_007"],
    ["multiplayer_overlays", "FM_Tat_M_017"],
    ["multiplayer_overlays", "FM_Tat_M_022"],
    ["multiplayer_overlays", "FM_Tat_M_039"],
    ["multiplayer_overlays", "FM_Tat_M_040"],
    ["multiplayer_overlays", "FM_Tat_M_042"],
    ["multiplayer_overlays", "FM_Tat_M_043"],
    ["mphipster_overlays", "FM_Hip_M_Tat_038"],
    ["mphipster_overlays", "FM_Hip_M_Tat_042"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_004_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_022_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_028_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_040_M"],
    ["mpbiker_overlays", "MP_MP_Biker_Tat_048_M"],
    ["mpchristmas2_overlays", "MP_Xmas2_M_Tat_014"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_006_M"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_026_M"],
    ["mpgunrunning_overlays", "MP_Gunrunning_Tattoo_030_M"],
    ["mplowrider_overlays", "MP_LR_Tat_017_M"],
    ["mplowrider_overlays", "MP_LR_Tat_023_M"],
    ["mplowrider2_overlays", "MP_LR_Tat_030_M"],
    ["mpluxe_overlays", "MP_LUXE_TAT_001_M"],
    ["mpbeach_overlays", "MP_Bea_F_RLeg_000"],
    ["mpluxe2_overlays", "MP_LUXE_TAT_023_M"],
    ["mpAirRaces_overlays", "MP_AirRaces_Tattoo_000_M"],
    ["mpAirRaces_overlays", "MP_AirRaces_Tattoo_001_M"],
    ["mpAirRaces_overlays", "MP_AirRaces_Tattoo_002_M"],
    ["mpAirRaces_overlays", "MP_AirRaces_Tattoo_003_M"],
    ["mpAirRaces_overlays", "MP_AirRaces_Tattoo_004_M"],
    ["mpAirRaces_overlays", "MP_AirRaces_Tattoo_005_M"],
    ["mpAirRaces_overlays", "MP_AirRaces_Tattoo_006_M"],
    ["mpAirRaces_overlays", "MP_AirRaces_Tattoo_007_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_000_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_001_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_002_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_003_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_004_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_005_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_006_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_007_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_008_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_009_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_010_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_011_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_012_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_013_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_014_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_015_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_016_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_017_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_018_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_019_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_020_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_021_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_022_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_023_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_024_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_025_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_026_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_027_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_028_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_029_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_030_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_031_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_032_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_033_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_034_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_035_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_036_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_037_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_038_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_039_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_040_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_041_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_042_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_043_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_044_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_045_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_046_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_047_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_048_M"],
    ["mpStunt_overlays", "MP_MP_Stunt_Tat_049_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_000_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_001_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_002_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_003_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_004_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_005_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_006_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_007_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_008_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_009_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_010_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_011_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_012_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_013_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_014_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_015_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_016_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_017_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_018_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_019_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_020_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_021_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_022_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_023_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_024_M"],
    ["mpSmuggler_overlays", "MP_Smuggler_Tattoo_025_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_000_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_001_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_002_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_003_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_004_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_005_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_006_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_007_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_008_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_009_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_010_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_011_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_012_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_013_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_014_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_015_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_016_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_017_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_018_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_019_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_020_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_021_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_022_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_023_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_024_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_025_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_026_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_027_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_028_M"],
    ["mpChristmas2017_overlays", "MP_Christmas2017_Tattoo_029_M"],
    ["mpbeach_overlays", "FM_Hair_Fuzz"]
]

zFramework.Core.Cloth.Models = [
    "mp_m_freemode_01",
    "mp_f_freemode_01",
    "csb_agent",
    "ig_amandatownley",
    "s_m_m_strpreach_01",
    "a_m_m_fatlatin_01",
    "a_f_m_beach_01",
    "a_f_m_bevhills_01",
    "a_f_m_bevhills_02",
    "a_f_m_bodybuild_01",
    "a_f_m_business_02",
    "a_f_m_downtown_01",
    "a_f_m_eastsa_01",
    "a_f_m_eastsa_02",
    "a_f_m_fatbla_01",
    "a_f_m_fatcult_01",
    "a_f_m_fatwhite_01",
    "a_f_m_ktown_01",
    "a_f_m_ktown_02",
    "a_f_m_prolhost_01",
    "a_f_m_salton_01",
    "a_f_m_skidrow_01",
    "a_f_m_soucent_01",
    "a_f_m_soucent_02",
    "a_f_m_soucentmc_01",
    "a_f_m_tourist_01",
    "a_f_m_tramp_01",
    "a_f_m_trampbeac_01",
    "a_f_o_genstreet_01",
    "a_f_o_indian_01",
    "a_f_o_ktown_01",
    "a_f_o_salton_01",
    "a_f_o_soucent_01",
    "a_f_o_soucent_02",
    "a_f_y_beach_01",
    "a_f_y_bevhills_01",
    "a_f_y_bevhills_02",
    "a_f_y_bevhills_03",
    "a_f_y_bevhills_04",
    "a_f_y_business_01",
    "a_f_y_business_02",
    "a_f_y_business_03",
    "a_f_y_business_04",
    "a_f_y_eastsa_01",
    "a_f_y_eastsa_02",
    "a_f_y_eastsa_03",
    "a_f_y_epsilon_01",
    "a_f_y_fitness_01",
    "a_f_y_fitness_02",
    "a_f_y_genhot_01",
    "a_f_y_golfer_01",
    "a_f_y_hiker_01",
    "a_f_y_hippie_01",
    "a_f_y_hipster_01",
    "a_f_y_hipster_02",
    "a_f_y_hipster_03",
    "a_f_y_hipster_04",
    "a_f_y_indian_01",
    "a_f_y_juggalo_01",
    "a_f_y_runner_01",
    "a_f_y_rurmeth_01",
    "a_f_y_scdressy_01",
    "a_f_y_skater_01",
    "a_f_y_soucent_01",
    "a_f_y_soucent_02",
    "a_f_y_soucent_03",
    "a_f_y_tennis_01",
    "a_f_y_topless_01",
    "a_f_y_tourist_01",
    "a_f_y_tourist_02",
    "a_f_y_vinewood_01",
    "a_f_y_vinewood_02",
    "a_f_y_vinewood_03",
    "a_f_y_vinewood_04",
    "a_f_y_yoga_01",
    "a_m_m_acult_01",
    "a_m_m_afriamer_01",
    "a_m_m_beach_01",
    "a_m_m_beach_02",
    "a_m_m_bevhills_01",
    "a_m_m_bevhills_02",
    "a_m_m_business_01",
    "a_m_m_eastsa_01",
    "a_m_m_eastsa_02",
    "a_m_m_farmer_01",
    "a_m_m_fatlatin_01",
    "a_m_m_genfat_01",
    "a_m_m_genfat_02",
    "a_m_m_golfer_01",
    "a_m_m_hasjew_01",
    "a_m_m_hillbilly_01",
    "a_m_m_hillbilly_02",
    "a_m_m_indian_01",
    "a_m_m_ktown_01",
    "a_m_m_malibu_01",
    "a_m_m_mexcntry_01",
    "a_m_m_mexlabor_01",
    "a_m_m_og_boss_01",
    "a_m_m_paparazzi_01",
    "a_m_m_polynesian_01",
    "a_m_m_prolhost_01",
    "a_m_m_rurmeth_01",
    "a_m_m_salton_01",
    "a_m_m_salton_02",
    "a_m_m_salton_03",
    "a_m_m_salton_04",
    "a_m_m_skater_01",
    "a_m_m_skidrow_01",
    "a_m_m_socenlat_01",
    "a_m_m_soucent_01",
    "a_m_m_soucent_02",
    "a_m_m_soucent_03",
    "a_m_m_soucent_04",
    "a_m_m_stlat_02",
    "a_m_m_tennis_01",
    "a_m_m_tourist_01",
    "a_m_m_tramp_01",
    "a_m_m_trampbeac_01",
    "a_m_m_tranvest_01",
    "a_m_m_tranvest_02",
    "a_m_o_acult_01",
    "a_m_o_acult_02",
    "a_m_o_beach_01",
    "a_m_o_genstreet_01",
    "a_m_o_ktown_01",
    "a_m_o_salton_01",
    "a_m_o_soucent_01",
    "a_m_o_soucent_02",
    "a_m_o_soucent_03",
    "a_m_o_tramp_01",
    "a_m_y_acult_01",
    "a_m_y_acult_02",
    "a_m_y_beach_01",
    "a_m_y_beach_02",
    "a_m_y_beach_03",
    "a_m_y_beachvesp_01",
    "a_m_y_beachvesp_02",
    "a_m_y_bevhills_01",
    "a_m_y_bevhills_02",
    "a_m_y_breakdance_01",
    "a_m_y_busicas_01",
    "a_m_y_business_01",
    "a_m_y_business_02",
    "a_m_y_business_03",
    "a_m_y_cyclist_01",
    "a_m_y_dhill_01",
    "a_m_y_downtown_01",
    "a_m_y_eastsa_01",
    "a_m_y_eastsa_02",
    "a_m_y_epsilon_01",
    "a_m_y_epsilon_02",
    "a_m_y_gay_01",
    "a_m_y_gay_02",
    "a_m_y_genstreet_01",
    "a_m_y_genstreet_02",
    "a_m_y_golfer_01",
    "a_m_y_hasjew_01",
    "a_m_y_hiker_01",
    "a_m_y_hippy_01",
    "a_m_y_hipster_01",
    "a_m_y_hipster_02",
    "a_m_y_hipster_03",
    "a_m_y_indian_01",
    "a_m_y_jetski_01",
    "a_m_y_juggalo_01",
    "a_m_y_ktown_01",
    "a_m_y_ktown_02",
    "a_m_y_latino_01",
    "a_m_y_methhead_01",
    "a_m_y_mexthug_01",
    "a_m_y_motox_01",
    "a_m_y_motox_02",
    "a_m_y_musclbeac_01",
    "a_m_y_musclbeac_02",
    "a_m_y_polynesian_01",
    "a_m_y_roadcyc_01",
    "a_m_y_runner_01",
    "a_m_y_runner_02",
    "a_m_y_salton_01",
    "a_m_y_skater_01",
    "a_m_y_skater_02",
    "a_m_y_soucent_01",
    "a_m_y_soucent_02",
    "a_m_y_soucent_03",
    "a_m_y_soucent_04",
    "a_m_y_stbla_01",
    "a_m_y_stbla_02",
    "a_m_y_stlat_01",
    "a_m_y_stwhi_01",
    "a_m_y_stwhi_02",
    "a_m_y_sunbathe_01",
    "a_m_y_surfer_01",
    "a_m_y_vindouche_01",
    "a_m_y_vinewood_01",
    "a_m_y_vinewood_02",
    "a_m_y_vinewood_03",
    "a_m_y_vinewood_04",
    "a_m_y_yoga_01",
    "g_f_importexport_01",
    "g_f_y_ballas_01",
    "g_f_y_families_01",
    "g_f_y_lost_01",
    "g_f_y_vagos_01",
    "g_m_importexport_01",
    "g_m_m_armboss_01",
    "g_m_m_armgoon_01",
    "g_m_m_armlieut_01",
    "g_m_m_chemwork_01",
    "g_m_m_chiboss_01",
    "g_m_m_chicold_01",
    "g_m_m_chigoon_01",
    "g_m_m_chigoon_02",
    "g_m_m_korboss_01",
    "g_m_m_mexboss_01",
    "g_m_m_mexboss_02",
    "g_m_y_armgoon_02",
    "g_m_y_azteca_01",
    "g_m_y_ballaeast_01",
    "g_m_y_ballaorig_01",
    "g_m_y_ballasout_01",
    "g_m_y_famca_01",
    "g_m_y_famdnf_01",
    "g_m_y_famfor_01",
    "g_m_y_korean_01",
    "g_m_y_korean_02",
    "g_m_y_korlieut_01",
    "g_m_y_lost_01",
    "g_m_y_lost_02",
    "g_m_y_lost_03",
    "g_m_y_mexgang_01",
    "g_m_y_mexgoon_01",
    "g_m_y_mexgoon_02",
    "g_m_y_mexgoon_03",
    "g_m_y_pologoon_01",
    "g_m_y_pologoon_02",
    "g_m_y_salvaboss_01",
    "g_m_y_salvagoon_01",
    "g_m_y_salvagoon_02",
    "g_m_y_salvagoon_03",
    "g_m_y_strpunk_01",
    "g_m_y_strpunk_02",
    "ig_abigail",
    "ig_amandatownley",
    "ig_andreas",
    "ig_ashley",
    "ig_ballasog",
    "ig_bankman",
    "ig_barry",
    "ig_benny",
    "ig_bestmen",
    "ig_beverly",
    "ig_brad",
    "ig_bride",
    "ig_car3guy1",
    "ig_car3guy2",
    "ig_chef",
    "ig_chengsr",
    "ig_chrisformage",
    "ig_clay",
    "ig_claypain",
    "ig_cletus",
    "ig_dale",
    "ig_davenorton",
    "ig_denise",
    "ig_devin",
    "ig_dom",
    "ig_dreyfuss",
    "ig_drfriedlander",
    "ig_fabien",
    "ig_fbisuit_01",
    "ig_floyd",
    "ig_g",
    "ig_groom",
    "ig_hao",
    "ig_hunter",
    "ig_janet",
    "ig_jay_norris",
    "ig_jewelass",
    "ig_jimmyboston",
    "ig_jimmydisanto",
    "ig_joeminuteman",
    "ig_josef",
    "ig_josh",
    "ig_kerrymcintosh",
    "ig_lamardavis",
    "ig_lazlow",
    "ig_lestercrest",
    "ig_lifeinvad_01",
    "ig_lifeinvad_02",
    "ig_magenta",
    "ig_malc",
    "ig_manuel",
    "ig_marnie",
    "ig_maryann",
    "ig_maude",
    "ig_michelle",
    "ig_milton",
    "ig_molly",
    "ig_mrk",
    "ig_mrs_thornhill",
    "ig_mrsphillips",
    "ig_natalia",
    "ig_nervousron",
    "ig_nigel",
    "ig_old_man1a",
    "ig_old_man2",
    "ig_omega",
    "ig_oneil",
    "ig_ortega",
    "ig_paper",
    "ig_patricia",
    "ig_priest",
    "ig_ramp_gang",
    "ig_ramp_hic",
    "ig_ramp_hipster",
    "ig_ramp_mex",
    "ig_roccopelosi",
    "ig_russiandrunk",
    "ig_screen_writer",
    "ig_solomon",
    "ig_stevehains",
    "ig_stretch",
    "ig_talina",
    "ig_tanisha",
    "ig_taocheng",
    "ig_taostranslator",
    "ig_tenniscoach",
    "ig_terry",
    "ig_tomepsilon",
    "ig_tonya",
    "ig_tracydisanto",
    "ig_trafficwarden",
    "ig_tylerdix",
    "ig_vagspeak",
    "ig_wade",
    "ig_zimbor",
    "mp_f_boatstaff_01",
    "mp_f_cardesign_01",
    "mp_f_chbar_01",
    "mp_f_counterfeit_01",
    "mp_f_execpa_01",
    "mp_f_forgery_01",
    "mp_f_weed_01",
    "mp_g_m_pros_01",
    "mp_m_counterfeit_01",
    "mp_m_exarmy_01",
    "mp_m_execpa_01",
    "mp_m_famdd_01",
    "mp_m_forgery_01",
    "mp_m_g_vagfun_01",
    "mp_m_shopkeep_01",
    "mp_m_waremech_01",
    "mp_m_weed_01",
    "s_f_m_fembarber",
    "s_f_m_maid_01",
    "s_f_m_shop_high",
    "s_f_m_sweatshop_01",
    "s_f_y_bartender_01",
    "s_f_y_hooker_01",
    "s_f_y_hooker_02",
    "s_f_y_hooker_03",
    "s_f_y_migrant_01",
    "s_f_y_movprem_01",
    "s_f_y_shop_low",
    "s_f_y_shop_mid",
    "s_f_y_sweatshop_01",
    "s_m_m_ammucountry",
    "s_m_m_autoshop_01",
    "s_m_m_autoshop_02",
    "s_m_m_bouncer_01",
    "s_m_m_ciasec_01",
    "s_m_m_cntrybar_01",
    "s_m_m_fiboffice_01",
    "s_m_m_fiboffice_02",
    "s_m_m_gaffer_01",
    "s_m_m_gardener_01",
    "s_m_m_hairdress_01",
    "s_m_m_highsec_01",
    "s_m_m_highsec_02",
    "s_m_m_janitor",
    "s_m_m_lathandy_01",
    "s_m_m_lifeinvad_01",
    "s_m_m_linecook",
    "s_m_m_lsmetro_01",
    "s_m_m_mariachi_01",
    "s_m_m_migrant_01",
    "s_m_m_movprem_01",
    "s_m_m_strpreach_01",
    "s_m_m_strvend_01",
    "s_m_m_trucker_01",
    "s_m_o_busker_01",
    "s_m_y_ammucity_01",
    "s_m_y_barman_01",
    "s_m_y_busboy_01",
    "s_m_y_chef_01",
    "s_m_y_dealer_01",
    "s_m_y_devinsec_01",
    "s_m_y_grip_01",
    "s_m_y_robber_01",
    "s_m_y_shop_mask",
    "s_m_y_strvend_01",
    "s_m_y_valet_01",
    "s_m_y_waiter_01",
    "s_m_y_winclean_01",
    "s_m_y_xmech_01",
    "s_m_y_xmech_02",
    "s_m_y_xmech_02_mp",
    "u_f_m_miranda",
    "u_f_m_promourn_01",
    "u_f_o_moviestar",
    "u_f_o_prolhost_01",
    "u_f_y_bikerchic",
    "u_f_y_comjane",
    "u_f_y_hotposh_01",
    "u_f_y_jewelass_01",
    "u_f_y_mistress",
    "u_f_y_poppymich",
    "u_f_y_princess",
    "u_f_y_spyactress",
    "u_m_m_aldinapoli",
    "u_m_m_bankman",
    "u_m_m_bikehire_01",
    "u_m_m_fibarchitect",
    "u_m_m_filmdirector",
    "u_m_m_glenstank_01",
    "u_m_m_griff_01",
    "u_m_m_jesus_01",
    "u_m_m_jewelsec_01",
    "u_m_m_jewelthief",
    "u_m_m_markfost",
    "u_m_m_partytarget",
    "u_m_m_promourn_01",
    "u_m_m_rivalpap",
    "u_m_m_spyactor",
    "u_m_m_willyfist",
    "u_m_o_finguru_01",
    "u_m_o_taphillbilly",
    "u_m_o_tramp_01",
    "u_m_y_abner",
    "u_m_y_antonb",
    "u_m_y_babyd",
    "u_m_y_baygor",
    "u_m_y_chip",
    "u_m_y_cyclist_01",
    "u_m_y_fibmugger_01",
    "u_m_y_guido_01",
    "u_m_y_gunvend_01",
    "u_m_y_hippie_01",
    "u_m_y_mani",
    "u_m_y_militarybum",
    "u_m_y_paparazzi",
    "u_m_y_party_01",
    "u_m_y_sbike",
    "u_m_y_tattoo_01",
    "s_m_y_cop_01",
    "s_m_y_blackops_01",
    "s_m_y_blackops_02",
    "s_m_y_blackops_03",
    "a_f_y_femaleagent",
    "mp_f_cocaine_01",
    "mp_f_execpa_02",
    "mp_f_helistaff_01",
    "mp_f_meth_01",
    "mp_f_weed_01",
    "mp_m_cocaine_01",
    "mp_m_counterfeit_01",
    "mp_m_meth_01",
    "mp_m_securoguard_01",
    "mp_m_weapexp_01",
    "mp_m_weapwork_01",
    "u_m_m_streetart_01",
    "ig_lestercrest_2",
    "ig_avon",
    "mp_m_avongoon",
    "mp_m_bogdangoon",
    "csb_jackhowitzer",
    "cs_amandatownley",
    "cs_andreas",
    "cs_ashley",
    "cs_bankman",
    "cs_barry",
    "cs_beverly",
    "cs_brad",
    "cs_bradcadaver",
    "cs_carbuyer",
    "cs_casey",
    "cs_chengsr",
    "cs_chrisformage",
    "cs_clay",
    "cs_dale",
    "cs_davenorton",
    "cs_debra",
    "cs_denise",
    "cs_devin",
    "cs_dom",
    "cs_dreyfuss",
    "cs_drfriedlander",
    "cs_fabien",
    "cs_fbisuit_01",
    "cs_floyd",
    "cs_guadalope",
    "cs_gurk",
    "cs_hunter",
    "cs_janet",
    "cs_jewelass",
    "cs_jimmyboston",
    "cs_jimmydisanto",
    "cs_joeminuteman",
    "cs_johnnyklebitz",
    "cs_josef",
    "cs_josh",
    "cs_lamardavis",
    "cs_lazlow",
    "cs_lestercrest",
    "cs_lifeinvad_01",
    "cs_magenta",
    "cs_manuel",
    "cs_marnie",
    "cs_martinmadrazo",
    "cs_maryann",
    "cs_michelle",
    "cs_milton",
    "cs_molly",
    "cs_movpremf_01",
    "cs_movpremmale",
    "cs_mrk",
    "cs_mrs_thornhill",
    "cs_mrsphillips",
    "cs_natalia",
    "cs_nervousron",
    "cs_nigel",
    "cs_old_man1a",
    "cs_old_man2",
    "cs_omega",
    "cs_orleans",
    "cs_paper",
    "cs_patricia",
    "cs_priest",
    "cs_prolsec_02",
    "cs_russiandrunk",
    "cs_siemonyetarian",
    "cs_solomon",
    "cs_stevehains",
    "cs_stretch",
    "cs_tanisha",
    "cs_taocheng",
    "cs_taostranslator",
    "cs_tenniscoach",
    "cs_terry",
    "cs_tom",
    "cs_tomepsilon",
    "cs_tracydisanto",
    "cs_wade",
    "cs_zimbor",
    "csb_abigail",
    "csb_anita",
    "csb_anton",
    "csb_ballasog",
    "csb_bride",
    "csb_burgerdrug",
    "csb_car3guy1",
    "csb_car3guy2",
    "csb_chef",
    "csb_chin_goon",
    "csb_cletus",
    "csb_cop",
    "csb_customer",
    "csb_denise_friend",
    "csb_fos_rep",
    "csb_g",
    "csb_groom",
    "csb_grove_str_dlr",
    "csb_hao",
    "csb_hugh",
    "csb_imran",
    "csb_janitor",
    "csb_maude",
    "csb_mweather",
    "csb_ortega",
    "csb_oscar",
    "csb_porndudes",
    "csb_prologuedriver",
    "csb_prolsec",
    "csb_ramp_gang",
    "csb_ramp_hic",
    "csb_ramp_hipster",
    "csb_ramp_marine",
    "csb_ramp_mex",
    "csb_reporter",
    "csb_roccopelosi",
    "csb_screen_writer",
    "csb_stripper_01",
    "csb_stripper_02",
    "csb_tonya",
    "csb_trafficwarden",
    "csb_vagspeak",
    "hc_driver",
    "hc_gunman",
    "hc_hacker",
    "ig_casey",
    "ig_johnnyklebitz",
    "ig_orleans",
    "ig_prolsec_02",
    "ig_siemonyetarian",
    "mp_f_deadhooker",
    "mp_f_misty_01",
    "mp_f_stripperlite",
    "mp_f_stripperlite",
    "mp_m_fibsec_01",
    "mp_s_m_armoured_01",
    "s_f_y_airhostess_01",
    "s_f_y_baywatch_01",
    "s_f_y_cop_01",
    "s_f_y_factory_01",
    "s_f_y_ranger_01",
    "s_f_y_scrubs_01",
    "s_f_y_sheriff_01",
    "s_f_y_stripper_01",
    "s_f_y_stripper_02",
    "s_f_y_stripperlite",
    "s_m_m_armoured_01",
    "s_m_m_armoured_02",
    "s_m_m_chemsec_01",
    "s_m_m_dockwork_01",
    "s_m_m_doctor_01",
    "s_m_m_gentransport",
    "s_m_m_marine_01",
    "s_m_m_marine_02",
    "s_m_m_movalien_01",
    "s_m_m_movspace_01",
    "s_m_m_paramedic_01",
    "s_m_m_pilot_01",
    "s_m_m_pilot_02",
    "s_m_m_postal_01",
    "s_m_m_postal_02",
    "s_m_m_prisguard_01",
    "s_m_m_scientist_01",
    "s_m_m_security_01",
    "s_m_m_snowcop_01",
    "s_m_m_strperf_01",
    "s_m_m_ups_01",
    "s_m_m_ups_02",
    "s_m_y_airworker",
    "s_m_y_armymech_01",
    "s_m_y_autopsy_01",
    "s_m_y_baywatch_01",
    "s_m_y_clown_01",
    "s_m_y_construct_01",
    "s_m_y_construct_02",
    "s_m_y_dockwork_01",
    "s_m_y_doorman_01",
    "s_m_y_dwservice_01",
    "s_m_y_dwservice_02",
    "s_m_y_factory_01",
    "s_m_y_fireman_01",
    "s_m_y_garbage",
    "s_m_y_hwaycop_01",
    "s_m_y_marine_01",
    "s_m_y_marine_02",
    "s_m_y_marine_03",
    "s_m_y_mime",
    "s_m_y_pestcont_01",
    "s_m_y_pilot_01",
    "s_m_y_prismuscl_01",
    "s_m_y_prisoner_01",
    "s_m_y_ranger_01",
    "s_m_y_sheriff_01",
    "s_m_y_uscg_01",
    "u_m_m_prolsec_01",
    "u_m_y_burgerdrug_01",
    "u_m_y_imporage",
    "u_m_y_justin",
    "u_m_y_prisoner_01",
    "u_m_y_proldriver_01",
    "u_m_y_rsranger_01",
    "u_m_y_staggrm_01",
    "a_f_y_clubcust_01",
    "a_f_y_clubcust_02",
    "a_f_y_clubcust_03",
    "ig_agent",
    "ig_mp_agent14",
    "ig_chef2",
    "ig_popov",
    "ig_karen_daniels",
    "ig_rashcosvki",
    "ig_money",
    "ig_paige",
    "ig_djblamadon",
    "ig_djblamryans",
    "ig_djblamrupert",
    "ig_djdixmanager",
    "ig_djsolfotios",
    "ig_djsoljakob",
    "ig_djsolmike",
    "ig_djsolrobt",
    "ig_djtalaurelia",
    "ig_djtalignazio",
    "ig_dix",
    "ig_englishdave",
    "ig_djgeneric_01",
    "ig_jimmyboston_02",
    "ig_kerrymcintosh_02",
    "ig_lacey_jones_02",
    "ig_lazlow_2",
    "ig_sol",
    "ig_djsolmanager",
    "ig_talcc",
    "ig_talmm",
    "ig_tylerdix_02",
    "ig_tonyprince",
    "ig_sacha",
    "u_m_y_juggernaut_01",
    "u_m_y_corpse_01",
    "u_m_m_doa_01",
    "u_m_m_edtoh",
    "u_m_y_smugmech_01",
    "u_m_o_filmnoir",
    "u_m_y_pogo_01",
    "u_m_y_zombie_01",
    "u_m_y_danceburl_01",
    "u_m_y_dancelthr_01",
    "u_m_y_dancerave_01",
    "mp_f_meth_01",
    "mp_m_boatstaff_01",
    "mp_f_bennymech_01",
    "csb_mp_agent14",
    "csb_avon",
    "csb_bogdan",
    "csb_chef2",
    "csb_popov",
    "cs_karen_daniels",
    "csb_rashcosvki",
    "csb_money",
    "csb_mrs_r",
    "csb_paige",
    "csb_undercover",
    "csb_djblamadon",
    "csb_dix",
    "csb_englishdave",
    "cs_lazlow_2",
    "csb_sol",
    "csb_talcc",
    "csb_talmm",
    "csb_tonyprince",
    "csb_alan",
    "csb_bryony",
    "s_m_m_ccrew_01",
    "s_m_m_fibsec_01",
    "s_m_y_swat_01",
    "s_m_y_clubbar_01",
    "s_m_y_waretech_01",
    "s_f_y_clubbar_01",
    "u_f_m_corpse_01",
    "u_f_y_corpse_01",
    "u_f_y_corpse_02",
    "u_f_m_miranda_02",
    "u_f_y_poppymich_02",
    "u_f_y_danceburl_01",
    "u_f_y_dancelthr_01",
    "u_f_y_dancerave_01",
    "a_m_y_clubcust_01",
    "a_m_y_clubcust_02",
    "a_m_y_clubcust_03"
];

zFramework.Core.Cloth.SetPedHairs = function(ped, drawableId, colorId, highlightId) {
    SetPedComponentVariation(ped, 2, drawableId, 0, 2);
    SetPedHairColor(ped, colorId, highlightId);
}

const drawables = [35, 37, 47, 48, 49, 52, 53, 54, 55, 56, 57, 58, 99, 102, 104, 106, 132, 130, 123, 117, 113, 112];
zFramework.Core.Cloth.SetPedMask = function(ped, drawableId, textureId, data) {
    const unk = data || zFramework.LocalPlayer.character && zFramework.LocalPlayer.character.c && zFramework.LocalPlayer.character.c[0];
    if (!unk) return;
    
    if (drawableId == 0) {
        SetPedHeadBlendData(
          playerPed,
          unk[0],
          unk[1],
          unk[2],
          unk[3],
          unk[4],
          unk[5],
          unk[6],
          unk[7],
          unk[8],
          false
        );
        SetPedComponentVariation(ped, 0, unk[0], 0, 2);
    } else if (drawables.find(id => id === drawableId)) {
        const unk2 = zFramework.LocalPlayer.sex == 0 && 0 || 33;
        SetPedHeadBlendData(
          playerPed,
          unk2,
          unk2,
          unk2,
          unk[3],
          unk[4],
          unk[5],
          unk[6],
          unk[7],
          unk[8],
          false
        );
        SetPedComponentVariation(ped, 0, unk2, 0, 2);
    }
    SetPedComponentVariation(ped, 1, drawableId, textureId, 2);
}

zFramework.Core.Cloth.SetPedDecorations = function(ped, data, clothes = null) {
    const playerData = data || zFramework.LocalPlayer.character;
    clothes = clothes || playerData.c && playerData.c[1] && playerData.c[1][0];
    ClearPedDecorations(ped);

    if (clothes && zFramework.LocalPlayer.sex <= 1) {
        let unk = {};
        for (const hairData of this.Hairs[zFramework.LocalPlayer.sex]) {
            if (hairData.ID == clothes) {
                unk = hairData;
                break;
            }
        }
        if (unk.collection)
            ApplyPedOverlay(ped, unk.collection, unk.overlay);
    }
    if (playerData.e && playerData.e[1] && typeof(playerData.e[1]) == "object") {
        for (const overlayId of playerData.e[1]) {
            if (this.Overlays[overlayId])
                ApplyPedOverlay(ped, this.Overlays[overlayId][0], this.Overlays[overlayId][1]);
        }
    }
    if (playerData.c && playerData.c[11] && playerData.c[11][0] && playerData.c[11][0].length > 0)
        SetPedDecoration(ped, playerData.c[11][0], playerData.c[11][1]);
}

zFramework.Core.Cloth.GetDefaultClothForComponent = function(component, sex) {
    sex = sex || zFramework.LocalPlayer.sex;
    if (sex > 1) return 0;
    const defaultCloth = this.DefaultClothes[sex][component - 1];
    
    return defaultCloth && (typeof(defaultCloth) === "object" && defaultCloth[0] || defaultCloth) || 0;
}

zFramework.Core.Cloth.GetDefaultClothForComponentWithTexture = function(texture, sex) {
    sex = sex || zFramework.LocalPlayer.sex;
    if (sex > 1) return [0, 0];

    const defaultCloth = this.DefaultClothes[sex][texture - 1];
    return defaultCloth && (typeof(defaultCloth) === "object" && defaultCloth || [(defaultCloth || 0), 0]) || [0, 0];
}

zFramework.Core.Cloth.SetSkin = function(data, options) {
    data = data && data.set || data || {};
    data.c = data.c || {}, data.p = data.p || {}, options = options || {};

    let canSetDecorations = false;
    const playerPed = options && options.ped || zFramework.LocalPlayer.pedId, playerSex = options.sex || zFramework.LocalPlayer.sex;
    const unk1 = playerSex <= 1 || options.ped;
    
    if (options.bl) {
        for (let i=0; i <= 12; i++) {
            if (!data.c[i] && i > 0 && i != 2)
                data.c[i] = this.GetDefaultClothForComponentWithTexture(i, playerSex);
        }
        for (const componentId of [0, 1, 2, 6, 7]) {
            if (!data.p[componentId])
                data.p[componentId] = [-1, 0];
        }
    }
    for (let i=0; i <= 12; i++) {
        const unk2 = data.c[i];
        if (unk2) {
            if (i == 0 && unk2.length == 9 && unk1)
                SetPedHeadBlendData(
                  playerPed,
                  unk2[0],
                  unk2[1],
                  unk2[2],
                  unk2[3],
                  unk2[4],
                  unk2[5],
                  unk2[6] + .0,
                  unk2[7] + .0,
                  unk2[8] + .0,
                  false
                );
            else if (i == 1 && unk1)
                this.SetPedMask(playerPed, unk2[0] || 0, unk2[2] || 0, data.c[0]);
            else if (i == 2 && unk1) {
                this.SetPedHairs(playerPed, unk2[0], unk2[1], unk2[2]);
                canSetDecorations = true;
            } else if (i == 12 && unk1)
                canSetDecorations = true;
            else {
                const drawableId = unk2[0] && parseInt(unk2[0]) || 0, textureId = unk2[1] && parseInt(unk2[1]);
                SetPedComponentVariation(playerPed, i, drawableId, textureId, 2);
            }
        }
    }
    for (const componentId of [0, 1, 2, 6, 7]) {
        const prop = data.p[componentId];
        if (prop) {
            const drawableId = prop[0] && parseInt(prop[0]) || 0, textureId = prop[1] && parseInt(prop[1]) || 0;
            if (drawableId > -1) SetPedPropIndex(playerPed, parseInt(componentId), drawableId, textureId, false);
            else ClearPedProp(playerPed, parseInt(componentId));
        }
    }
    for (let overlayId=0; overlayId <= 12; overlayId++) {
        const unk2 = data.h && data.h[overlayId];
        if (unk2) {
            const index = unk2[0] && parseInt(unk2[0]) || -1, opacity = unk2[1] && parseFloat(unk2[1]) || 1.0, colorId = unk2[2] && parseInt(unk2[2]) || 0;
            SetPedHeadOverlay(playerPed, overlayId, index, opacity);
            SetPedHeadOverlayColor(playerPed, overlayId, GM.Cloth.OverlayTypes[Uk7e + 1], colorId, colorId);
        }
    }
    if (data.e) {
        if (unk1 && data.e[0] && typeof(data.e[0]) == "number")
            SetPedEyeColor(playerPed, data.e[0]);
        if (data.e[1] && typeof(data.e[1]) == "object")
            canSetDecorations = true;
    }
    if (canSetDecorations) this.SetPedDecorations(playerPed, data);
}

function unk_function1(data) {
    console.log(data.length);
    let dM;
    for (const [U, _u] in Object.entries(data)) {
        if (typeof(_u) == "object" && tonumber(U)) {
            dM = data[8] && data.length > 1 && 8 || tonumber(U);
            break;
        }
    }

    return dM;
}

zFramework.Core.Cloth.PlayClothAnim = async function(ped, name, enfiled, data) {
    ClearPedTasks(ped);

    let anims, time, flag;
    if (name == "Masque") {
        anims = enfiled && ["missfbi4", "takeoff_mask"] || ["mp_masks@on_foot", "put_on_mask"];
        time = enfiled && 550 || 600;
    } else if (name == "Accessoire") {
        const e = unk_function1(data);
        if (e == 0) {
            anims = ["veh@bike@common@front@base", "take_off_helmet_stand"];
            time = enfiled && 800 || 200;
        }
        else if (e == 1) {
            anims = ["clothingspecs", "try_glasses_neutral_b"];
            time = 900;
        }
    }

    if (time && anims) {
        zFramework.Functions.PlayAnim(anims, null, flag || 48);
        await Delay(time);
    }
}